export const additionalFeatures = [
  'a mystical forest with glowing trees and hidden fairy dwellings',
  'a frozen landscape dominated by towering ice castles and aurora skies',
  'an underwater kingdom with colorful coral reefs and ancient ruins',
  'a vast desert with mysterious, shifting sand dunes and a hidden oasis',
  'a vibrant alien planet with exotic flora and floating islands',
  'a medieval village during a festive market day, bustling with activity',
  'a post-apocalyptic wasteland with remnants of a once advanced civilization',
  'a serene Japanese garden during cherry blossom season, with a tranquil koi pond',
  'a bustling pirate port with ships and a lively market',
  'a whimsical candy land filled with edible landscapes and chocolate rivers',
  'a steampunk city with intricate gear-driven machines and airships',
  'an enchanted castle surrounded by a moat and magical defenses',
  'a wild jungle with ancient temples and mysterious wildlife',
  'a space station orbiting a distant, unexplored planet',
  'a gothic city at night, shrouded in fog and lit by gas lamps',
  'a magical library with endless shelves and floating books',
  'a vibrant carnival with rides, games, and colorful tents',
  'a tranquil mountain retreat with breathtaking views and peaceful monasteries',
  'a lost Atlantis-like city submerged and rediscovered under the sea',
  'an enchanted meadow with luminescent flowers and magical creatures',
  'a futuristic city with neon lights, hover cars, and towering skyscrapers',
  'an ancient Greek city with marble temples and mythical gods',
  'a whimsical chocolate factory with rivers of chocolate and candy trees',
  'a high-tech space colony on Mars with domed habitats and red landscapes',
  'a haunted Victorian mansion with secret passages and ghostly apparitions',
  'a secret superhero hideout with advanced technology and hidden chambers',
  'a lush rainforest with towering waterfalls and exotic birds',
  'a mystical Asian temple with dragons and floating lanterns',
  'a vibrant music festival with stages, crowds, and festive decorations',
  'an old Western town with saloons, horse carriages, and dusty streets',
  'a dreamy cloudscape with floating islands and mythical creatures',
  'a Renaissance fair with knights, jesters, and medieval tournaments',
  'a prehistoric landscape with dinosaurs and lush primeval forests',
  'a magical winter wonderland with ice sculptures and northern lights',
  'an abandoned amusement park reclaimed by nature and mystery',
  'a surreal landscape with floating rocks and gravity-defying structures',
  'an ancient Egyptian setting with pyramids, sphinxes, and pharaohs',
  'a lush vineyard with rolling hills, grapevines, and rustic cottages',
  'a cyberpunk slum with neon signs, makeshift structures, and drones',
];
