# Default values for myapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.gitlab.com/constellation-hackathon-2023/backend/http-image-module
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
