---
stages:
  - deploy

variables:
  DOCKER_RENOVATE_IMG: "renovate/renovate:35.118.0"
  RENOVATE_LOG_FILE: "renovate-log.ndjson"
  RENOVATE_LOG_FILE_LEVEL: "debug"
  LOG_LEVEL: "info"
  RENOVATE_BASE_DIR: "$CI_PROJECT_DIR/renovate"
  RENOVATE_CONFIG_FILE: "config.js"
  RENOVATE_PR_HOURLY_LIMIT: 5

renovate-job:
  stage: "deploy"
  image: "${DOCKER_RENOVATE_IMG}"
  script:
    - "renovate"
  artifacts:
    when: "always"
    expire_in: "1d"
    paths:
      - "${RENOVATE_LOG_FILE}"
  cache:
    key: "${CI_COMMIT_REF_SLUG}-renovate"
    paths:
      - "${RENOVATE_BASE_DIR}/cache/renovate/repository/"
  rules:
    - if: "$CI_PIPELINE_SOURCE == \"web\""
      when: "manual"
    - if: "$CI_PIPELINE_SOURCE == \"schedule\""
...
